config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/auth/:name/callback' => 'omniauths#callback'
  get '/load' => 'omniauths#load'
  get '/uninstall' => 'omniauths#uninstall'
  resource :omniauth
  get '/default_template' => 'home#default_template'
  get '/default_shipment_template' => 'home#default_shipment_template'
  get '/toggle/:id' => "templates#toggle_active", as: :toggle_active
  get '/event_types/list' => 'templates#list_event_types'

  resources :templates

  resources :hooks do
    collection do
      post 'order_created'
      post 'shipment_created'
    end
  end

end

app/views/templates/_event_types.html.erb
<% event_types = event.present? ? event.event_types : [] %>
<% event_types_final = (params[:template].present? && params[:template][:event_id].present? && event_types.blank?) ? Event.find(params[:template][:event_id]).event_types : event_types %>
<% event_type_id = event_type.new_record? ? nil : event_type.id %>
<% event_type_id_final = (params[:template].present? && params[:template][:event_type_id].present? && event_type_id.blank?) ? params[:template][:event_type_id].to_i : event_type_id %>
<% msg_present = flash['danger'].present? && flash['danger'].include?('Event type can\'t be blank')  %>
<div class='form-group <%= 'has-error' if msg_present %>'>
  <%= select_tag 'template[event_type_id]', options_from_collection_for_select(event_types_final, "id", "name", event_type_id_final), prompt: 'Please Select Event Type', class: 'form-control select optional event_type_id'%>
</div>
<script type="text/javascript">
$("#template_event_type_id").change(function() {
  var selected = $("#template_event_type_id option:selected").text();
  if (selected && $("#template_event_id option:selected").text() == 'order' && $("#template_event_type_id option:selected").text() == 'order created') {
    console.log('test1');
    $('#summernote').code($("#default-template-body-order").html());
    console.log('test1---------------------------');
    $("#template_body").val($('#summernote').code());
  } else if( selected && $("#template_event_id option:selected").text() == 'shipment' && $("#template_event_type_id option:selected").text() == 'shipment created'){
    console.log('test2');
    $('#summernote').code($("#default-template-body-shipment").html());
    console.log('test2--------------------');
    $("#template_body").val($('#summernote').code());
  }else{
    console.log('test3');
    $('#summernote').code("");
    $("#template_body").val($('#summernote').code());
  }
});
$("#template_event_id").change(function() {
  var selected = $("#template_event_type_id option:selected").text();
  if (selected && $("#template_event_id option:selected").text() == 'order' && $("#template_event_type_id option:selected").text() == 'order created') {
    $('#summernote').code($("#default-template-body-order").html());
    $("#template_body").val($('#summernote').code());
  } else if( selected && $("#template_event_id option:selected").text() == 'shipment' && $("#template_event_type_id option:selected").text() == 'shipment created'){

    $('#summernote').code($("#default-template-body-shipment").html());
    $("#template_body").val($('#summernote').code());
  }else{
    console.log('test3');
    $('#summernote').code("");
    $("#template_body").val($('#summernote').code());
  }
});
</script>

app/views/templates/_form.html.erb
<div class="row">
	<div class="col-lg-12">
		<div class="hpanel">
			<div class="panel-body">
				<%= simple_form_for(@template, html: {class: 'form-horizontal'}) do |f| %>
				<div class="form-group">
					<label class="col-sm-2 control-label">Name<span class="required-field">*</span></label>
					<div class="col-sm-10">
						<%= f.input :name, required: true, label: false, :error => false %>
					</div>
					<div class="clearfix"></div>
						<label class="col-sm-2 control-label">Event<span class="required-field">*</span></label>
						<% event_missing = flash['danger'].present? && flash['danger'].include?('Event can\'t be blank')%>
						<div class="col-sm-10 <%= 'error' if event_missing %>">
							<% event = @template.new_record? ? Event.new : @template.event %>
							<% event_final = (params[:template].present? && params[:template][:event_id].blank? && event.blank?) ? Event.new : event %>
							<% event_id = event_final.new_record? ? nil : event_final.id %>
							<% event_id_final = (params[:template].present? && params[:template][:event_id].present? && event_id.blank?) ? params[:template][:event_id].to_i : event_id %>
							<div class='form-group <%= 'has-error' if event_missing %>'>
							<%= f.select :event_id, options_for_select(Event.pluck(:name, :id), selected: event_id_final), {include_blank: 'Please Select Event' }, id: 'template_event_id', class: 'form-control', required: 'required' %>
						</div>
					</div>
					<div class="clearfix"></div>
					<label class="col-sm-2 control-label">Event Type<span class="required-field">*</span></label>
					<div class="col-sm-10" id="event-type-list">
						<% event_type = @template.new_record? ? EventType.new : @event_type%>
						<%= render partial: 'templates/event_types', locals: { event: event, event_type: event_type }%>
					</div>
					<div class="clearfix"></div>
					<label class="col-sm-2 control-label">Available Variables</label>
					<div class="col-sm-10">
						<div class="form-group">
							<%= select_tag 'template[variables]', options_for_select(::Template::AVAILABLE_TEMPLATE_VARIABLES), include_blank: 'Select Variable to Insert', class: 'form-control select optional' %>
						</div>
					</div>
					<div class="clearfix"></div>
					<label class="col-sm-2 control-label">Subject<span class="required-field">*</span></label>
					<div class="col-sm-10">
						<%= f.input :subject, label: false, placeholder: "Write the subject here..." , :error => false%>
					</div>
					<div class="clearfix"></div>
					<label class="col-sm-2 control-label">Body<span class="required-field">*</span></label>
					<div class="col-sm-10">
						<div class="form-group">
							<div id="summernote"></div>
						</div>
						<%= f.input :body, as: :hidden, label: false, required:false %>
					</div>
				</div>
          <div class="clearfix"></div>
          <label class="col-sm-2 control-label"></label>
					<div class="col-sm-10">
						<div class="form-action">
							<%= f.button :submit, "Save" %>
							<%= link_to 'Cancel', templates_path, class: 'btn btn-default', method: :get %>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>
<% unless @template.new_record? %>
	<% if @template.event_id == 1 && @template.event_type_id == 1 %>
		<div id="default-template-body-order" style="display: none;"><%= @template.body.html_safe%></div>
	<% else %>
		<div id="default-template-body-order" style="display: none;"><%= ::Template::DEFAULT_TEMPLATES[:order][:body].html_safe%></div>
	<% end %>
	<% if @template.event_id == 2 && @template.event_type_id == 2 %>
		<div id="default-template-body-shipment" style="display: none;"><%= @template.body.html_safe%> </div>
	<% else %>
		<div id="default-template-body-shipment" style="display: none;"><%= ::Template::DEFAULT_TEMPLATES[:shipment][:body].html_safe%></div>
	<% end %>
<% else %>
	<% if @template.event_id == 1 && @template.event_type_id == 1%>
		<div id="default-template-body-order" style="display: none;"><%= @template.body.html_safe%></div>
	<% else%>
		<div id="default-template-body-order" style="display: none;"><%= ::Template::DEFAULT_TEMPLATES[:order][:body].html_safe%></div>
	<% end %>
	<% if @template.event_id == 2 && @template.event_type_id == 2%>
		<div id="default-template-body-shipment" style="display: none;"><%= @template.body.html_safe%></div>
	<% else %>
		<div id="default-template-body-shipment" style="display: none;"><%= ::Template::DEFAULT_TEMPLATES[:shipment][:body].html_safe%></div>
	<% end %>
<% end %>
<script>
$(document).ready(function(){
	$("#template_body").val($('#summernote').code());
	$('#summernote').summernote({
		placeholder : 'Default template will be displayed soon once you select event and event type...'
	});

	$('.note-editable').on('keyup', function() {
		$("#template_body").val($('#summernote').code());
	});
	$('.note-editable').on('keyup', function() {
		$("#template_body").val($('#summernote').code());
	});
	<% if flash['danger'].present? && (flash['danger'].include?('Body can\'t be blank') ||
		flash['danger'].include?('Please check your template body. There are some wrong variables found.')) %>
		$('.note-editor').addClass('custom-error');
	<% end %>
  BigCommerce.Template.InsertAtCaretPosition();
 	$("#template_event_id option:selected").val();
	$('#template_event_id').change(function(){
		var event =	this.options[this.options.selectedIndex].value
		if(event){
			$.ajax({
				url: "/event_types/list",
				data: { event: event, template_id: "<%= @template.id %>" }
			})
		}
	});
	var selected = $("#template_event_type_id option:selected").text();
	console.log('testtetstest')
	if ($(selected && $("#template_event_id option:selected").text() == 'order' && "#template_event_type_id option:selected").text() == 'order created') {
		console.log('erty')
		$('#summernote').code($("#default-template-body-order").html());
		$("#template_body").val($('#summernote').code());
	} else if($(selected && $("#template_event_id option:selected").text() == 'shipment' && "#template_event_type_id option:selected").text() == 'shipment created') {
		console.log('fsdfsdf')
		$('#summernote').code($("#default-template-body-shipment").html());
		$("#template_body").val($('#summernote').code());
	}else{
		console.log('5678')
		$('#summernote').code("");
		$("#template_body").val($('#summernote').code());
	}
});
</script>

app/views/templates/edit.html.erb
<div class="small-header transition animated fadeIn">
	<div class="hpanel">
		<div class="panel-body">
			<div id="hbreadcrumb" class="pull-right">
				<ol class="hbreadcrumb breadcrumb">
					<li>
						<a href="index.html">Dashboard</a>
					</li>
					<li>
						<span>Templates</span>
					</li>
					<li class="active">
						<span>Edit</span>
					</li>
				</ol>
			</div>
			<h2 class="font-light m-b-xs"> Edit Template </h2>
			<small>Edit this template</small>
		</div>
	</div>
</div>

<div class="content animate-panel">
	<div>
		<%= render 'form' %>
	</div>
</div>

app/views/templates/index.html.erb
<div class="normalheader transition animated fadeIn">
	<div class="hpanel">
		<div class="panel-body">
			<a class="small-header-action" href="">
			<div class="clip-header">
				<i class="fa fa-arrow-up"></i>
			</div> </a>

			<div id="hbreadcrumb" class="pull-right m-t-lg">
				<ol class="hbreadcrumb breadcrumb">
					<li>
						<a href="javascript:;">Home</a>
					</li>
					<li>
						<span>Templates</span>
					</li>
					<li class="active">
						<span>Listing</span>
					</li>
				</ol>
			</div>
			<h2 class="font-light m-b-xs"> Templates </h2>
			<small>Available templates for the store</small>
		</div>
	</div>
</div>

<div class="content animate-panel">
	<div class="row">
		<div class="col-lg-12">
			<div class="hpanel">
				<div class="panel-body">
					<%= link_to 'New Template', new_template_path, class: 'btn btn-success pull-right', method: :get %>
					<div class="clearfix"></div>
					<div class="table-responsive top5">
						<table cellpadding="1" cellspacing="1" class="table table-bordered table-striped">
							<thead>
								<tr>
									<th>#</th>
									<th>Name</th>
									<th>Event</th>
									<th>Event Type</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
								<% unless @templates.empty? %>
									<% @templates.each_with_index do |template, index| %>
										<% confirm_msg = template.active? ? 'Are you sure you want to deactivate this template?' : 'Are you sure you want to activate this template?' %>
										<% tooltip_msg = template.active? ? 'This is currently active template.' : 'This is currently inactive template.' %>
										<tr>
											<td><%= index + 1%></td>
											<td><%= template.name %></td>
											<td><%= template.event.name if template.event.present? %></td>
											<td><%= template.event_type.name if template.event_type.present? %></td>
											<td>
												<%= link_to template, method: :get, style: 'font-size: 25px;' do %>
												  <i class="pe-7s-look" title="Preview"></i>
												<% end %>
												<% unless template.active? %>
													<%= link_to template_path(template), method: :delete, style: 'font-size: 25px;', data: { confirm: 'Are you sure you want to delete this template?'} do %>
													  <i class="fa fa-trash" title="Delete"></i>
													<% end %>
												<% end %>
												<%= link_to edit_template_path(template), method: :get, style: 'font-size: 25px;' do %>
													<i class="fa fa-pencil-square-o" title="Edit"></i>
												<% end %>
												<%= link_to toggle_active_path(template.id), method: :get, style: 'font-size: 25px;', data: { confirm: "#{confirm_msg}" } do %>
													<% sym = template.active? ? "fa-check" : "fa-check disabled" %>
													<i class="fa <%= sym %>" title="<%= tooltip_msg %>"></i>
												<% end %>
											</td>
										</tr>
									<% end %>
								<% else %>
								<tr>
									<td colspan="5">No templates available. Please add.</td>
								</tr>
								<% end %>
							</tbody>
							<tfoot>
								<tr>
									<td class="footable-visible" colspan="5">
									<div class="pull-right">
										<%= paginate @templates %>
									</div></td>
								</tr>
							</tfoot>
						</table>
					</div>
				</div>
				<div class="panel-footer">
					Table - <%= @templates.count%> rows
				</div>
			</div>
		</div>
	</div>
</div>

app/views/templates/list_event_types.js.erb
$("#event-type-list").html("<%= escape_javascript(render partial: 'templates/event_types', locals: { event: @event, event_type: @event_type } ) %>");

app/views/templates/new.html.erb
<div class="small-header transition animated fadeIn">
	<div class="hpanel">
		<div class="panel-body">
			<div id="hbreadcrumb" class="pull-right">
				<ol class="hbreadcrumb breadcrumb">
					<li>
						<a href="#">Dashboard</a>
					</li>
					<li>
						<span>Templates</span>
					</li>
					<li class="active">
						<span>New</span>
					</li>
				</ol>
			</div>
			<h2 class="font-light m-b-xs"> New Template </h2>
			<small>Add new template for the store</small>
		</div>
	</div>
</div>

<div class="content animate-panel">
	<div>
    <%= render 'form' %>
	</div>
</div>

app/views/templates/show.html.erb
<div class="normalheader transition animated fadeIn">
	<div class="hpanel">
		<div class="panel-body">
			<a class="small-header-action" href="javascript:;">
			<div class="clip-header">
				<i class="fa fa-arrow-up"></i>
			</div> </a>

			<div id="hbreadcrumb" class="pull-right m-t-lg">
				<ol class="hbreadcrumb breadcrumb">
					<li>
						<a href="javascript:;">Dashboard</a>
					</li>
					<li>
						<span>Template</span>
					</li>
					<li class="active">
						<span>Show</span>
					</li>
				</ol>
			</div>
			<h2 class="font-light m-b-xs"> Email Template </h2>
			<small>Email Template - View</small>
		</div>
	</div>
</div>
<div class="content animate-panel">
	<div class="row">
		<div class="col-md-12">
			<div class="hpanel email-compose">
				<div class="panel-heading hbuilt">
					<div class="p-xs h4">
						Template Content
					</div>
				</div>
				<div class="border-top border-left border-right bg-light">
					<div class="p-m">
						<div>
							<span class="font-extra-bold">Event: </span>
							<%= @template.event.name%>
						</div>
						<div>
							<span class="font-extra-bold">Event Type: </span>
							<%= @template.event_type.name%>
						</div>
						<div>
							<span class="font-extra-bold">Subject: </span>
							<%= @template.subject%>
						</div>
						<div>
							<span class="font-extra-bold">Status: </span>
							<%= @template.active? ? "Active" : "InActive"%>
						</div>
					</div>
				</div>
				<div class="panel-body">
					<div>
						<%= @template.body.html_safe%>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>